### ISSUE TITLE
É esperada a entrada duplicada em arquivo para mesmo dia?

### ISSUE THREAD

**Issue by jesuino** [LabProdam/DadosDaCiclovia#1]
Olá,

Eu estou consumindo esse repositório em um projetinho que estou criando para visualizar o avanço das nossas queridas ciclovias. No meu banco eu coloquei uma restrição de coluna única na tabela de ocorrência para que a ocorrência onde a mesma data não pode acontecer para aquele ciclovia naquele dia.

No entanto, essa restrição falhou no arquivo /2015/06/2015-06-01.csv:

```
$ grep '2015-06-01 07:39:11' . -r
./2015/06/2015-06-01.csv:3302,1,1,"2015-06-01 07:39:11",45,37,81,0,"1529280"
./2015/06/2015-06-01.csv:3303,1,1,"2015-06-01 07:39:11",45,38,83,0,"1529291"
```

Não tenho problemas em ter essa duplicata no meu banco de dados, pois posso evitar possíveis desvios de dados de outras formas, mas seria isso esperado? Se sim, vou ajustar meu banco de dados. Talvez seria uma questão de adicionar os milissegundos na data?

Obrigado!

**Comment by pnspinelli** [comment]
Tudo bom?

Isso era esperado sim. Dois objetos diferentes foram detectados no mesmo segundo. Ambas as ocorrências possuem IDs e características geométricas distintas, fornecendo fortes indícios de que não há erro de detecção.
Sugiro utilizar a primeira coluna (a dos números 3302 e 3303) como chave única, vez que ela representa justamente esse papel no nosso banco de dados (único para cada local).
Consideraremos a utilização de milissegundos em revisões futuras.

Obrigado

**Comment by jesuino** [comment]
Muito obrigado pela resposta. Nossa aplicação já está no ar :)

http://estatisticas-cicloviassp.rhcloud.com/
